stages:
  - build
  - test
  - report
  - deploy

.base:
  image: ruby:2.6.3
  cache:
    key: gems_and_packages
    paths:
      - apt-cache/
      - vendor/ruby
    policy: pull
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"

.base_minimal:
  image: alpine:latest
  cache: {}

.base_db:
  extends: .base
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: unac_gitlab
    POSTGRES_USER: unac
    POSTGRES_PASSWORD: unac
    RAILS_ENV: gitlab
  before_script:
    - apt-get update -qq && apt-get install -yqq nodejs
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec rake db:setup

################### BUILD ################################

build:rubocop:
  extends: .base
  stage: build
  cache:
    policy: pull-push
  script:
    - bundle exec rubocop

build:assets_precompile:
  extends: .base_db
  stage: build
  script:
    - bundle exec rake assets:precompile

test:bundle_audit:
  extends: .base
  allow_failure: true
  script:
    - bundle exec bundle audit check --update

################### TEST ################################

test:brakeman:
  extends: .base
  stage: test
  allow_failure: true
  artifacts:
    name: brakeman_report
    when: always
    paths:
      - brakeman/
  only:
    - master
  script:
    - bundle exec brakeman --format html -o brakeman/index.html

test:dawnscanner:
  extends: .base
  stage: test
  allow_failure: true
  artifacts:
    name: dawnscanner_report
    when: always
    paths:
      - dawnscanner
  only:
    - master
  script:
    - mkdir dawnscanner
    - bundle exec dawn --html -zF dawnscanner/index.html .

################### REPORT ################################

pages:
  extends: .base_minimal
  stage: report
  allow_failure: true
  dependencies:
    - test:brakeman
    - test:dawnscanner
    - test:erd
    - test:rspec
  artifacts:
    name: my_app_artifacts
    paths:
      - public/brakeman
      - public/coverage
      - public/dawnscanner
      - public/erd.pdf
  only:
    - master
  script:
    - mv brakeman public/ || true
    - mv coverage public/ || true
    - mv dawnscanner public/ || true
    - mv erd.pdf public/ || true

################### DEPLOY ################################

deploy:staging:
  extends: .base
  stage: deploy
  only:
    - staging
  script:
    - echo "Deploying to Staging..."

deploy:production:
  extends: .base
  stage: deploy
  when: manual
  environment:
    name: production
    url: https://unac-staging.ydrazil.fr
  only:
    - master
  script:
    - echo "Deploying to Production..."

# include:
#   - template: Dependency-Scanning.gitlab-ci.yml

# bundler-audit-dependency_scanning:
#   variables:
#     SECURE_LOG_LEVEL: error