default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: unac
  host: postgres

development:
  <<: *default
  database: unac_backend_development
  password: unac

test:
  <<: *default
  database: unac_backend_test
  password: unac

production:
  <<: *default
  database: unac_backend_production
  password: <%= ENV['UNAC_BACKEND_DATABASE_PASSWORD'] %>
