default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: unac_backend_development
  password: postgres

test:
  <<: *default
  database: unac_backend_test
  password: postgres

staging:
  <<: *default
  database: unac_backend_staging
  password: Rails.application.credentials.heroku[:database_password]
  user: Rails.application.credentials.heroku[:database_user]
  host: Rails.application.credentials.heroku[:database_host]

production:
  <<: *default
  database: unac_backend_production
  password: Rails.application.credentials.heroku[:database_password]
  user: Rails.application.credentials.heroku[:database_user]
  host: Rails.application.credentials.heroku[:database_host]
