#!/bin/bash

echo -e "🤖 [RUBOCOP] --> Init (wait a second)"

FAILS=`docker-compose run engine rubocop -a | grep 'no offenses detected' -o | awk '{print $1}'`

if [ "$FAILS" == "no" ]; then
  echo -e "🤖 [RUBOCOP] --> 👍 approved."
  exit 0
else
  echo -e "🤖 [RUBOCOP] --> ✋ You've $FAILS offenses!!!\a"
  exit 1
fi
